# https://taskfile.dev

version: '3'

tasks:
  make-windsor-init-gif:
    desc: Builds all gif files
    cmds:
      - vhs docs/img/home-assistant/vhs/windsor-init.tape -o docs/img/home-assistant/windsor-init.gif

  make-windsor-up-gif:
    desc: Builds all gif files
    cmds:
      - vhs docs/img/home-assistant/vhs/windsor-up.tape -o docs/img/home-assistant/windsor-up.gif

  make-port-forwarding-gif:
    desc: Builds all gif files
    cmds:
      - vhs docs/img/home-assistant/vhs/port-forwarding.tape -o docs/img/home-assistant/port-forwarding.gif

  make-windsor-down-gif:
    desc: Builds all gif files
    cmds:
      - vhs docs/img/home-assistant/vhs/windsor-down.tape -o docs/img/home-assistant/windsor-down.gif

  make-check-ha-pod-gif:
    desc: Builds all gif files
    cmds:
      - vhs docs/img/home-assistant/vhs/check-ha-pod.tape -o docs/img/home-assistant/check-ha-pod.gif

  help:
    desc: VHS related commands
    cmds:
      - |
        echo "VHS"
        echo ""
        echo "    task vhs:make-windsor-init-gif"
        echo "    task vhs:make-windsor-up-gif"
        echo "    task vhs:make-port-forwarding-gif"
        echo "    task vhs:make-windsor-down-gif"
        echo "    task vhs:make-check-ha-pod-gif"
        echo ""
        echo "Also see [vhs docs](https://pkg.go.dev/github.com/charmbracelet/vhs#readme-tutorial)"
    silent: true
