# https://taskfile.dev

version: '3'

tasks:
  clean:
    desc: Clean up Docker images and containers
    cmds:
      - docker kill $(docker ps -q) && docker system prune -af

  #-----------------------------------------------------------------------------------------------------------------------
  # Docker
  #-----------------------------------------------------------------------------------------------------------------------

  help:
    desc: Docker releated commands
    cmds:
      - |
        echo "Docker"
        echo ""
        echo "    task docker:clean"
    silent: true
